apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: database
spec:
  containers:
    - name: app
      image: k8s.gcr.io/busybox
      command: ['sh', '-c', 'env && sleep 8000']
      envFrom:
      - secretRef:
          name: app-secret
      env:
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: username
            optional: false # same as default; "app-secret" must exist
                            # and include a key named "username"
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: password
            optional: false # same as default; "appsecret" must exist
                            # and include a key named "password"
